// 评分表管理
export const tableManage = {
  id: 6,
  name: '推广服务商等级评分表',
  desc: '推广服务商等级评分表',
  header: [
    {
      column_id: 16,
      name: '指标类别',
      sort_order: 1,
    },
    {
      column_id: 17,
      name: '具体项目',
      sort_order: 2,
    },
    {
      column_id: 18,
      name: '分数标准',
      sort_order: 3,
    },
  ],
  cell: [
    {
      id: 253,
      column_id: 16,
      content: '基础信息分析',
      sort_order: 1,
      level: 1,
      pid: 0,
      children: [
        {
          id: 254,
          column_id: 17,
          content:
            '经营资质(经营范围)：推广、技术服务、医药信息咨询、市场营销策划、企业营销策划、企业服务、企业咨询、会议及展览服务、企业管理、市场调查等',
          sort_order: 1,
          level: 2,
          pid: 253,
          children: [
            {
              id: 255,
              column_id: 18,
              content: '包含经营范围中的5项(含）以上',
              sort_order: 1,
              level: 3,
              pid: 254,
            },
            {
              id: 256,
              column_id: 18,
              content: '包含经营范围中的5项以下',
              sort_order: 2,
              level: 3,
              pid: 254,
            },
          ],
        },
        {
          id: 257,
          column_id: 17,
          content: '*注册地址及实际办公场所',
          sort_order: 2,
          level: 2,
          pid: 253,
          children: [
            {
              id: 258,
              column_id: 18,
              content:
                '*注册地与实际办公场所一致，且与推广区域一致或相近，实际办公场所为商业区且规范真实',
              sort_order: 1,
              level: 3,
              pid: 257,
            },
            {
              id: 259,
              column_id: 18,
              content: '注册地与实际办公场所不一致',
              sort_order: 2,
              level: 3,
              pid: 257,
            },
          ],
        },
        {
          id: 260,
          column_id: 17,
          content: '成立时间',
          sort_order: 3,
          level: 2,
          pid: 253,
          children: [
            {
              id: 261,
              column_id: 18,
              content: '*已成立3年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 260,
            },
            {
              id: 262,
              column_id: 18,
              content: '已成立1-3年',
              sort_order: 2,
              level: 3,
              pid: 260,
            },
            {
              id: 263,
              column_id: 18,
              content: '签协议当年成立',
              sort_order: 3,
              level: 3,
              pid: 260,
            },
          ],
        },
        {
          id: 264,
          column_id: 17,
          content: '与长典合作年限',
          sort_order: 4,
          level: 2,
          pid: 253,
          children: [
            {
              id: 265,
              column_id: 18,
              content: '2年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 264,
            },
            {
              id: 266,
              column_id: 18,
              content: '2年以下',
              sort_order: 2,
              level: 3,
              pid: 264,
            },
          ],
        },
        {
          id: 267,
          column_id: 17,
          content: '*单位类型及纳税人资质',
          sort_order: 5,
          level: 2,
          pid: 253,
          children: [
            {
              id: 268,
              column_id: 18,
              content: '*有限责任公司等--一般纳税人',
              sort_order: 1,
              level: 3,
              pid: 267,
            },
            {
              id: 269,
              column_id: 18,
              content: '有限责任公司--小规模纳税人',
              sort_order: 2,
              level: 3,
              pid: 267,
            },
          ],
        },
        {
          id: 270,
          column_id: 17,
          content: '年营业收入',
          sort_order: 6,
          level: 2,
          pid: 253,
          children: [
            {
              id: 271,
              column_id: 18,
              content: '500万（含）以上',
              sort_order: 1,
              level: 3,
              pid: 270,
            },
            {
              id: 272,
              column_id: 18,
              content: '120万~500万',
              sort_order: 2,
              level: 3,
              pid: 270,
            },
            {
              id: 273,
              column_id: 18,
              content: '120万（含）以下',
              sort_order: 3,
              level: 3,
              pid: 270,
            },
          ],
        },
        {
          id: 274,
          column_id: 17,
          content: '*员工人数（实际缴纳社保人数）',
          sort_order: 7,
          level: 2,
          pid: 253,
          children: [
            {
              id: 275,
              column_id: 18,
              content: '*10人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 274,
            },
            {
              id: 276,
              column_id: 18,
              content: '4-10人',
              sort_order: 2,
              level: 3,
              pid: 274,
            },
            {
              id: 277,
              column_id: 18,
              content: '3人（含）以下',
              sort_order: 3,
              level: 3,
              pid: 274,
            },
          ],
        },
        {
          id: 278,
          column_id: 17,
          content: '推广人员人数',
          sort_order: 8,
          level: 2,
          pid: 253,
          children: [
            {
              id: 279,
              column_id: 18,
              content: '5人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 278,
            },
            {
              id: 280,
              column_id: 18,
              content: '5人以下',
              sort_order: 2,
              level: 3,
              pid: 278,
            },
          ],
        },
        {
          id: 281,
          column_id: 17,
          content: '*推广人员的学历或者技能等专业能力',
          sort_order: 9,
          level: 2,
          pid: 253,
          children: [
            {
              id: 282,
              column_id: 18,
              content:
                '*占公司推广人员总人数50%以上，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 1,
              level: 3,
              pid: 281,
            },
            {
              id: 283,
              column_id: 18,
              content:
                '占公司推广人员总人数30%-50%，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 2,
              level: 3,
              pid: 281,
            },
            {
              id: 284,
              column_id: 18,
              content: '30%以下',
              sort_order: 3,
              level: 3,
              pid: 281,
            },
            {
              id: 285,
              column_id: 18,
              content: '不具有相关专业学历和证书',
              sort_order: 4,
              level: 3,
              pid: 281,
            },
          ],
        },
        {
          id: 286,
          column_id: 17,
          content: '推广方案',
          sort_order: 10,
          level: 2,
          pid: 253,
          children: [
            {
              id: 287,
              column_id: 18,
              content: '有推广方案，且方案专业性强产品适用度高',
              sort_order: 1,
              level: 3,
              pid: 286,
            },
            {
              id: 288,
              column_id: 18,
              content: '有提供',
              sort_order: 2,
              level: 3,
              pid: 286,
            },
          ],
        },
      ],
    },
    {
      id: 289,
      column_id: 16,
      content: '管理分析',
      sort_order: 2,
      level: 1,
      pid: 0,
      children: [
        {
          id: 290,
          column_id: 17,
          content: '*组织结构',
          sort_order: 1,
          level: 2,
          pid: 289,
          children: [
            {
              id: 291,
              column_id: 18,
              content: '有，且有专门推广部门',
              sort_order: 1,
              level: 3,
              pid: 290,
            },
            {
              id: 292,
              column_id: 18,
              content: '有',
              sort_order: 2,
              level: 3,
              pid: 290,
            },
          ],
        },
        {
          id: 293,
          column_id: 17,
          content: '*财务制度',
          sort_order: 2,
          level: 2,
          pid: 289,
          children: [
            {
              id: 294,
              column_id: 18,
              content: '财务制度健全',
              sort_order: 1,
              level: 3,
              pid: 293,
            },
          ],
        },
        {
          id: 295,
          column_id: 17,
          content: '*合规制度',
          sort_order: 3,
          level: 2,
          pid: 289,
          children: [
            {
              id: 296,
              column_id: 18,
              content: '合规制度健全',
              sort_order: 1,
              level: 3,
              pid: 295,
            },
          ],
        },
        {
          id: 297,
          column_id: 17,
          content: '*培训',
          sort_order: 4,
          level: 2,
          pid: 289,
          children: [
            {
              id: 298,
              column_id: 18,
              content: '业务/合规培训',
              sort_order: 1,
              level: 3,
              pid: 297,
            },
          ],
        },
      ],
    },
    {
      id: 299,
      column_id: 16,
      content: '配合度分析',
      sort_order: 3,
      level: 1,
      pid: 0,
      children: [
        {
          id: 300,
          column_id: 17,
          content: '提交的资料真实性、符合度',
          sort_order: 1,
          level: 2,
          pid: 299,
          children: [
            {
              id: 301,
              column_id: 18,
              content: '各类资料按时提交且真实，各服务项目配合度好',
              sort_order: 1,
              level: 3,
              pid: 300,
            },
            {
              id: 302,
              column_id: 18,
              content: '较为及时提交及符合要求',
              sort_order: 2,
              level: 3,
              pid: 300,
            },
            {
              id: 303,
              column_id: 18,
              content: '不按时提交或不符合要求及配合度较差',
              sort_order: 3,
              level: 3,
              pid: 300,
            },
          ],
        },
      ],
    },
  ],
  score_criteria: {
    criteria_column_id: 17,
    max_score: 100,
    total: [
      {
        cell_id: 254,
        score: 8,
      },
      {
        cell_id: 257,
        score: 10,
      },
      {
        cell_id: 260,
        score: 5,
      },
      {
        cell_id: 264,
        score: 5,
      },
      {
        cell_id: 267,
        score: 15,
      },
      {
        cell_id: 270,
        score: 10,
      },
      {
        cell_id: 274,
        score: 10,
      },
      {
        cell_id: 278,
        score: 5,
      },
      {
        cell_id: 281,
        score: 6,
      },
      {
        cell_id: 286,
        score: 6,
      },
      {
        cell_id: 290,
        score: 4,
      },
      {
        cell_id: 293,
        score: 3,
      },
      {
        cell_id: 295,
        score: 3,
      },
      {
        cell_id: 297,
        score: 3,
      },
      {
        cell_id: 300,
        score: 7,
      },
    ],
    detail: [
      {
        cell_id: 255,
        score: 8,
      },
      {
        cell_id: 256,
        score: 6,
      },
      {
        cell_id: 258,
        score: 10,
      },
      {
        cell_id: 259,
        score: 7,
      },
      {
        cell_id: 261,
        score: 5,
      },
      {
        cell_id: 262,
        score: 3,
      },
      {
        cell_id: 263,
        score: 2,
      },
      {
        cell_id: 265,
        score: 5,
      },
      {
        cell_id: 266,
        score: 3,
      },
      {
        cell_id: 268,
        score: 15,
      },
      {
        cell_id: 269,
        score: 10,
      },
      {
        cell_id: 271,
        score: 10,
      },
      {
        cell_id: 272,
        score: 8,
      },
      {
        cell_id: 273,
        score: 5,
      },
      {
        cell_id: 275,
        score: 10,
      },
      {
        cell_id: 276,
        score: 8,
      },
      {
        cell_id: 277,
        score: 5,
      },
      {
        cell_id: 279,
        score: 5,
      },
      {
        cell_id: 280,
        score: 3,
      },
      {
        cell_id: 282,
        score: 6,
      },
      {
        cell_id: 283,
        score: 5,
      },
      {
        cell_id: 284,
        score: 4,
      },
      {
        cell_id: 285,
        score: 3,
      },
      {
        cell_id: 287,
        score: 6,
      },
      {
        cell_id: 288,
        score: 4,
      },
      {
        cell_id: 291,
        score: 4,
      },
      {
        cell_id: 292,
        score: 2,
      },
      {
        cell_id: 294,
        score: 3,
      },
      {
        cell_id: 296,
        score: 3,
      },
      {
        cell_id: 298,
        score: 3,
      },
      {
        cell_id: 301,
        score: 7,
      },
      {
        cell_id: 302,
        score: 4,
      },
      {
        cell_id: 303,
        score: 3,
      },
    ],
  },
}
// 评分详情
export const tableDetail = {
  id: 6,
  name: '推广服务商等级评分表',
  desc: '推广服务商等级评分表',
  header: [
    {
      column_id: 16,
      name: '指标类别',
      sort_order: 1,
    },
    {
      column_id: 17,
      name: '具体项目',
      sort_order: 2,
    },
    {
      column_id: 18,
      name: '分数标准',
      sort_order: 3,
    },
  ],
  cell: [
    {
      id: 253,
      column_id: 16,
      content: '基础信息分析',
      sort_order: 1,
      level: 1,
      pid: 0,
      children: [
        {
          id: 254,
          column_id: 17,
          content:
            '经营资质(经营范围)：推广、技术服务、医药信息咨询、市场营销策划、企业营销策划、企业服务、企业咨询、会议及展览服务、企业管理、市场调查等',
          sort_order: 1,
          level: 2,
          pid: 253,
          children: [
            {
              id: 255,
              column_id: 18,
              content: '包含经营范围中的5项(含）以上',
              sort_order: 1,
              level: 3,
              pid: 254,
            },
            {
              id: 256,
              column_id: 18,
              content: '包含经营范围中的5项以下',
              sort_order: 2,
              level: 3,
              pid: 254,
            },
          ],
        },
        {
          id: 257,
          column_id: 17,
          content: '*注册地址及实际办公场所',
          sort_order: 2,
          level: 2,
          pid: 253,
          children: [
            {
              id: 258,
              column_id: 18,
              content:
                '*注册地与实际办公场所一致，且与推广区域一致或相近，实际办公场所为商业区且规范真实',
              sort_order: 1,
              level: 3,
              pid: 257,
            },
            {
              id: 259,
              column_id: 18,
              content: '注册地与实际办公场所不一致',
              sort_order: 2,
              level: 3,
              pid: 257,
            },
          ],
        },
        {
          id: 260,
          column_id: 17,
          content: '成立时间',
          sort_order: 3,
          level: 2,
          pid: 253,
          children: [
            {
              id: 261,
              column_id: 18,
              content: '*已成立3年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 260,
            },
            {
              id: 262,
              column_id: 18,
              content: '已成立1-3年',
              sort_order: 2,
              level: 3,
              pid: 260,
            },
            {
              id: 263,
              column_id: 18,
              content: '签协议当年成立',
              sort_order: 3,
              level: 3,
              pid: 260,
            },
          ],
        },
        {
          id: 264,
          column_id: 17,
          content: '与长典合作年限',
          sort_order: 4,
          level: 2,
          pid: 253,
          children: [
            {
              id: 265,
              column_id: 18,
              content: '2年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 264,
            },
            {
              id: 266,
              column_id: 18,
              content: '2年以下',
              sort_order: 2,
              level: 3,
              pid: 264,
            },
          ],
        },
        {
          id: 267,
          column_id: 17,
          content: '*单位类型及纳税人资质',
          sort_order: 5,
          level: 2,
          pid: 253,
          children: [
            {
              id: 268,
              column_id: 18,
              content: '*有限责任公司等--一般纳税人',
              sort_order: 1,
              level: 3,
              pid: 267,
            },
            {
              id: 269,
              column_id: 18,
              content: '有限责任公司--小规模纳税人',
              sort_order: 2,
              level: 3,
              pid: 267,
            },
          ],
        },
        {
          id: 270,
          column_id: 17,
          content: '年营业收入',
          sort_order: 6,
          level: 2,
          pid: 253,
          children: [
            {
              id: 271,
              column_id: 18,
              content: '500万（含）以上',
              sort_order: 1,
              level: 3,
              pid: 270,
            },
            {
              id: 272,
              column_id: 18,
              content: '120万~500万',
              sort_order: 2,
              level: 3,
              pid: 270,
            },
            {
              id: 273,
              column_id: 18,
              content: '120万（含）以下',
              sort_order: 3,
              level: 3,
              pid: 270,
            },
          ],
        },
        {
          id: 274,
          column_id: 17,
          content: '*员工人数（实际缴纳社保人数）',
          sort_order: 7,
          level: 2,
          pid: 253,
          children: [
            {
              id: 275,
              column_id: 18,
              content: '*10人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 274,
            },
            {
              id: 276,
              column_id: 18,
              content: '4-10人',
              sort_order: 2,
              level: 3,
              pid: 274,
            },
            {
              id: 277,
              column_id: 18,
              content: '3人（含）以下',
              sort_order: 3,
              level: 3,
              pid: 274,
            },
          ],
        },
        {
          id: 278,
          column_id: 17,
          content: '推广人员人数',
          sort_order: 8,
          level: 2,
          pid: 253,
          children: [
            {
              id: 279,
              column_id: 18,
              content: '5人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 278,
            },
            {
              id: 280,
              column_id: 18,
              content: '5人以下',
              sort_order: 2,
              level: 3,
              pid: 278,
            },
          ],
        },
        {
          id: 281,
          column_id: 17,
          content: '*推广人员的学历或者技能等专业能力',
          sort_order: 9,
          level: 2,
          pid: 253,
          children: [
            {
              id: 282,
              column_id: 18,
              content:
                '*占公司推广人员总人数50%以上，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 1,
              level: 3,
              pid: 281,
            },
            {
              id: 283,
              column_id: 18,
              content:
                '占公司推广人员总人数30%-50%，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 2,
              level: 3,
              pid: 281,
            },
            {
              id: 284,
              column_id: 18,
              content: '30%以下',
              sort_order: 3,
              level: 3,
              pid: 281,
            },
            {
              id: 285,
              column_id: 18,
              content: '不具有相关专业学历和证书',
              sort_order: 4,
              level: 3,
              pid: 281,
            },
          ],
        },
        {
          id: 286,
          column_id: 17,
          content: '推广方案',
          sort_order: 10,
          level: 2,
          pid: 253,
          children: [
            {
              id: 287,
              column_id: 18,
              content: '有推广方案，且方案专业性强产品适用度高',
              sort_order: 1,
              level: 3,
              pid: 286,
            },
            {
              id: 288,
              column_id: 18,
              content: '有提供',
              sort_order: 2,
              level: 3,
              pid: 286,
            },
          ],
        },
      ],
    },
    {
      id: 289,
      column_id: 16,
      content: '管理分析',
      sort_order: 2,
      level: 1,
      pid: 0,
      children: [
        {
          id: 290,
          column_id: 17,
          content: '*组织结构',
          sort_order: 1,
          level: 2,
          pid: 289,
          children: [
            {
              id: 291,
              column_id: 18,
              content: '有，且有专门推广部门',
              sort_order: 1,
              level: 3,
              pid: 290,
            },
            {
              id: 292,
              column_id: 18,
              content: '有',
              sort_order: 2,
              level: 3,
              pid: 290,
            },
          ],
        },
        {
          id: 293,
          column_id: 17,
          content: '*财务制度',
          sort_order: 2,
          level: 2,
          pid: 289,
          children: [
            {
              id: 294,
              column_id: 18,
              content: '财务制度健全',
              sort_order: 1,
              level: 3,
              pid: 293,
            },
          ],
        },
        {
          id: 295,
          column_id: 17,
          content: '*合规制度',
          sort_order: 3,
          level: 2,
          pid: 289,
          children: [
            {
              id: 296,
              column_id: 18,
              content: '合规制度健全',
              sort_order: 1,
              level: 3,
              pid: 295,
            },
          ],
        },
        {
          id: 297,
          column_id: 17,
          content: '*培训',
          sort_order: 4,
          level: 2,
          pid: 289,
          children: [
            {
              id: 298,
              column_id: 18,
              content: '业务/合规培训',
              sort_order: 1,
              level: 3,
              pid: 297,
            },
          ],
        },
      ],
    },
    {
      id: 299,
      column_id: 16,
      content: '配合度分析',
      sort_order: 3,
      level: 1,
      pid: 0,
      children: [
        {
          id: 300,
          column_id: 17,
          content: '提交的资料真实性、符合度',
          sort_order: 1,
          level: 2,
          pid: 299,
          children: [
            {
              id: 301,
              column_id: 18,
              content: '各类资料按时提交且真实，各服务项目配合度好',
              sort_order: 1,
              level: 3,
              pid: 300,
            },
            {
              id: 302,
              column_id: 18,
              content: '较为及时提交及符合要求',
              sort_order: 2,
              level: 3,
              pid: 300,
            },
            {
              id: 303,
              column_id: 18,
              content: '不按时提交或不符合要求及配合度较差',
              sort_order: 3,
              level: 3,
              pid: 300,
            },
          ],
        },
      ],
    },
  ],
  score_criteria: {
    criteria_column_id: 17,
    max_score: 100,
    total: [
      {
        cell_id: 254,
        score: 8,
      },
      {
        cell_id: 257,
        score: 10,
      },
      {
        cell_id: 260,
        score: 5,
      },
      {
        cell_id: 264,
        score: 5,
      },
      {
        cell_id: 267,
        score: 15,
      },
      {
        cell_id: 270,
        score: 10,
      },
      {
        cell_id: 274,
        score: 10,
      },
      {
        cell_id: 278,
        score: 5,
      },
      {
        cell_id: 281,
        score: 6,
      },
      {
        cell_id: 286,
        score: 6,
      },
      {
        cell_id: 290,
        score: 4,
      },
      {
        cell_id: 293,
        score: 3,
      },
      {
        cell_id: 295,
        score: 3,
      },
      {
        cell_id: 297,
        score: 3,
      },
      {
        cell_id: 300,
        score: 7,
      },
    ],
    detail: [
      {
        cell_id: 255,
        score: 8,
      },
      {
        cell_id: 256,
        score: 6,
      },
      {
        cell_id: 258,
        score: 10,
      },
      {
        cell_id: 259,
        score: 7,
      },
      {
        cell_id: 261,
        score: 5,
      },
      {
        cell_id: 262,
        score: 3,
      },
      {
        cell_id: 263,
        score: 2,
      },
      {
        cell_id: 265,
        score: 5,
      },
      {
        cell_id: 266,
        score: 3,
      },
      {
        cell_id: 268,
        score: 15,
      },
      {
        cell_id: 269,
        score: 10,
      },
      {
        cell_id: 271,
        score: 10,
      },
      {
        cell_id: 272,
        score: 8,
      },
      {
        cell_id: 273,
        score: 5,
      },
      {
        cell_id: 275,
        score: 10,
      },
      {
        cell_id: 276,
        score: 8,
      },
      {
        cell_id: 277,
        score: 5,
      },
      {
        cell_id: 279,
        score: 5,
      },
      {
        cell_id: 280,
        score: 3,
      },
      {
        cell_id: 282,
        score: 6,
      },
      {
        cell_id: 283,
        score: 5,
      },
      {
        cell_id: 284,
        score: 4,
      },
      {
        cell_id: 285,
        score: 3,
      },
      {
        cell_id: 287,
        score: 6,
      },
      {
        cell_id: 288,
        score: 4,
      },
      {
        cell_id: 291,
        score: 4,
      },
      {
        cell_id: 292,
        score: 2,
      },
      {
        cell_id: 294,
        score: 3,
      },
      {
        cell_id: 296,
        score: 3,
      },
      {
        cell_id: 298,
        score: 3,
      },
      {
        cell_id: 301,
        score: 7,
      },
      {
        cell_id: 302,
        score: 4,
      },
      {
        cell_id: 303,
        score: 3,
      },
    ],
  },
  recordsInfo: [
    {
      record_id: 98,
      score_at: '2024-01-11 15:05:24',
      scorer_name: '李岩军1',
      score: 95,
    },
    {
      record_id: 97,
      score_at: '2024-01-11 14:54:45',
      scorer_name: '李岩军1',
      score: 92,
    },
    {
      record_id: 96,
      score_at: '2024-01-11 14:53:43',
      scorer_name: '李岩军1',
      score: 0,
    },
    {
      record_id: 92,
      score_at: '2023-12-25 17:41:42',
      scorer_name: '李岩军1',
      score: 0,
    },
    {
      record_id: 91,
      score_at: '2023-12-22 16:41:28',
      scorer_name: '李岩军1',
      score: 19,
    },
    {
      record_id: 90,
      score_at: '2023-12-22 16:41:20',
      scorer_name: '李岩军1',
      score: 0,
    },
    {
      record_id: 89,
      score_at: '2023-12-22 16:40:05',
      scorer_name: '李岩军1',
      score: 3,
    },
    {
      record_id: 88,
      score_at: '2023-12-22 16:40:00',
      scorer_name: '李岩军1',
      score: 0,
    },
    {
      record_id: 87,
      score_at: '2023-12-22 16:39:48',
      scorer_name: '李岩军1',
      score: 32,
    },
    {
      record_id: 86,
      score_at: '2023-12-22 16:39:33',
      scorer_name: '李岩军1',
      score: 14,
    },
    {
      record_id: 85,
      score_at: '2023-12-22 16:39:23',
      scorer_name: '李岩军1',
      score: 35,
    },
    {
      record_id: 84,
      score_at: '2023-12-22 16:39:01',
      scorer_name: '李岩军1',
      score: 0,
    },
    {
      record_id: 83,
      score_at: '2023-12-22 16:38:58',
      scorer_name: '李岩军1',
      score: 0,
    },
    {
      record_id: 82,
      score_at: '2023-12-22 16:38:45',
      scorer_name: '李岩军1',
      score: 22,
    },
    {
      record_id: 81,
      score_at: '2023-12-22 16:38:32',
      scorer_name: '李岩军1',
      score: 87,
    },
    {
      record_id: 80,
      score_at: '2023-12-22 16:38:05',
      scorer_name: '李岩军1',
      score: 83,
    },
    {
      record_id: 79,
      score_at: '2023-12-22 16:30:52',
      scorer_name: '李岩军1',
      score: 65,
    },
    {
      record_id: 78,
      score_at: '2023-12-22 14:22:30',
      scorer_name: '李岩军1',
      score: 100,
    },
  ],
  scoreRecords: [
    {
      cell_id: 254,
      scores: [8, 6, 0, 0, 6, 0, 0, 0, 6, 6, 6, 0, 0, 6, 6, 8, 6, 8],
    },
    {
      cell_id: 257,
      scores: [10, 10, 0, 0, 0, 0, 0, 0, 10, 0, 10, 0, 0, 10, 10, 7, 7, 10],
    },
    {
      cell_id: 260,
      scores: [5, 5, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 3, 5, 3, 2, 5],
    },
    {
      cell_id: 264,
      scores: [3, 5, 0, 0, 0, 0, 3, 0, 3, 3, 0, 0, 0, 3, 3, 5, 3, 5],
    },
    {
      cell_id: 267,
      scores: [15, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 10, 10, 15],
    },
    {
      cell_id: 270,
      scores: [10, 10, 0, 0, 10, 0, 0, 0, 8, 0, 8, 0, 0, 0, 8, 10, 8, 10],
    },
    {
      cell_id: 274,
      scores: [10, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 10, 5, 10],
    },
    {
      cell_id: 278,
      scores: [3, 3, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 3, 3, 3, 5],
    },
    {
      cell_id: 281,
      scores: [5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 5, 6, 3, 6],
    },
    {
      cell_id: 286,
      scores: [6, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 4, 4, 6],
    },
    {
      cell_id: 290,
      scores: [4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 4, 4, 2, 4],
    },
    {
      cell_id: 293,
      scores: [3, 3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3],
    },
    {
      cell_id: 295,
      scores: [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 3, 3, 3],
    },
    {
      cell_id: 297,
      scores: [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3],
    },
    {
      cell_id: 300,
      scores: [7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 3, 7],
    },
  ],
}
// 立即评分
export const tableRating = {
  id: 6,
  name: '推广服务商等级评分表',
  desc: '推广服务商等级评分表',
  header: [
    {
      column_id: 16,
      name: '指标类别',
      sort_order: 1,
    },
    {
      column_id: 17,
      name: '具体项目',
      sort_order: 2,
    },
    {
      column_id: 18,
      name: '分数标准',
      sort_order: 3,
    },
  ],
  cell: [
    {
      id: 253,
      column_id: 16,
      content: '基础信息分析',
      sort_order: 1,
      level: 1,
      pid: 0,
      children: [
        {
          id: 254,
          column_id: 17,
          content:
            '经营资质(经营范围)：推广、技术服务、医药信息咨询、市场营销策划、企业营销策划、企业服务、企业咨询、会议及展览服务、企业管理、市场调查等',
          sort_order: 1,
          level: 2,
          pid: 253,
          children: [
            {
              id: 255,
              column_id: 18,
              content: '包含经营范围中的5项(含）以上',
              sort_order: 1,
              level: 3,
              pid: 254,
            },
            {
              id: 256,
              column_id: 18,
              content: '包含经营范围中的5项以下',
              sort_order: 2,
              level: 3,
              pid: 254,
            },
          ],
        },
        {
          id: 257,
          column_id: 17,
          content: '*注册地址及实际办公场所',
          sort_order: 2,
          level: 2,
          pid: 253,
          children: [
            {
              id: 258,
              column_id: 18,
              content:
                '*注册地与实际办公场所一致，且与推广区域一致或相近，实际办公场所为商业区且规范真实',
              sort_order: 1,
              level: 3,
              pid: 257,
            },
            {
              id: 259,
              column_id: 18,
              content: '注册地与实际办公场所不一致',
              sort_order: 2,
              level: 3,
              pid: 257,
            },
          ],
        },
        {
          id: 260,
          column_id: 17,
          content: '成立时间',
          sort_order: 3,
          level: 2,
          pid: 253,
          children: [
            {
              id: 261,
              column_id: 18,
              content: '*已成立3年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 260,
            },
            {
              id: 262,
              column_id: 18,
              content: '已成立1-3年',
              sort_order: 2,
              level: 3,
              pid: 260,
            },
            {
              id: 263,
              column_id: 18,
              content: '签协议当年成立',
              sort_order: 3,
              level: 3,
              pid: 260,
            },
          ],
        },
        {
          id: 264,
          column_id: 17,
          content: '与长典合作年限',
          sort_order: 4,
          level: 2,
          pid: 253,
          children: [
            {
              id: 265,
              column_id: 18,
              content: '2年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 264,
            },
            {
              id: 266,
              column_id: 18,
              content: '2年以下',
              sort_order: 2,
              level: 3,
              pid: 264,
            },
          ],
        },
        {
          id: 267,
          column_id: 17,
          content: '*单位类型及纳税人资质',
          sort_order: 5,
          level: 2,
          pid: 253,
          children: [
            {
              id: 268,
              column_id: 18,
              content: '*有限责任公司等--一般纳税人',
              sort_order: 1,
              level: 3,
              pid: 267,
            },
            {
              id: 269,
              column_id: 18,
              content: '有限责任公司--小规模纳税人',
              sort_order: 2,
              level: 3,
              pid: 267,
            },
          ],
        },
        {
          id: 270,
          column_id: 17,
          content: '年营业收入',
          sort_order: 6,
          level: 2,
          pid: 253,
          children: [
            {
              id: 271,
              column_id: 18,
              content: '500万（含）以上',
              sort_order: 1,
              level: 3,
              pid: 270,
            },
            {
              id: 272,
              column_id: 18,
              content: '120万~500万',
              sort_order: 2,
              level: 3,
              pid: 270,
            },
            {
              id: 273,
              column_id: 18,
              content: '120万（含）以下',
              sort_order: 3,
              level: 3,
              pid: 270,
            },
          ],
        },
        {
          id: 274,
          column_id: 17,
          content: '*员工人数（实际缴纳社保人数）',
          sort_order: 7,
          level: 2,
          pid: 253,
          children: [
            {
              id: 275,
              column_id: 18,
              content: '*10人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 274,
            },
            {
              id: 276,
              column_id: 18,
              content: '4-10人',
              sort_order: 2,
              level: 3,
              pid: 274,
            },
            {
              id: 277,
              column_id: 18,
              content: '3人（含）以下',
              sort_order: 3,
              level: 3,
              pid: 274,
            },
          ],
        },
        {
          id: 278,
          column_id: 17,
          content: '推广人员人数',
          sort_order: 8,
          level: 2,
          pid: 253,
          children: [
            {
              id: 279,
              column_id: 18,
              content: '5人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 278,
            },
            {
              id: 280,
              column_id: 18,
              content: '5人以下',
              sort_order: 2,
              level: 3,
              pid: 278,
            },
          ],
        },
        {
          id: 281,
          column_id: 17,
          content: '*推广人员的学历或者技能等专业能力',
          sort_order: 9,
          level: 2,
          pid: 253,
          children: [
            {
              id: 282,
              column_id: 18,
              content:
                '*占公司推广人员总人数50%以上，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 1,
              level: 3,
              pid: 281,
            },
            {
              id: 283,
              column_id: 18,
              content:
                '占公司推广人员总人数30%-50%，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 2,
              level: 3,
              pid: 281,
            },
            {
              id: 284,
              column_id: 18,
              content: '30%以下',
              sort_order: 3,
              level: 3,
              pid: 281,
            },
            {
              id: 285,
              column_id: 18,
              content: '不具有相关专业学历和证书',
              sort_order: 4,
              level: 3,
              pid: 281,
            },
          ],
        },
        {
          id: 286,
          column_id: 17,
          content: '推广方案',
          sort_order: 10,
          level: 2,
          pid: 253,
          children: [
            {
              id: 287,
              column_id: 18,
              content: '有推广方案，且方案专业性强产品适用度高',
              sort_order: 1,
              level: 3,
              pid: 286,
            },
            {
              id: 288,
              column_id: 18,
              content: '有提供',
              sort_order: 2,
              level: 3,
              pid: 286,
            },
          ],
        },
      ],
    },
    {
      id: 289,
      column_id: 16,
      content: '管理分析',
      sort_order: 2,
      level: 1,
      pid: 0,
      children: [
        {
          id: 290,
          column_id: 17,
          content: '*组织结构',
          sort_order: 1,
          level: 2,
          pid: 289,
          children: [
            {
              id: 291,
              column_id: 18,
              content: '有，且有专门推广部门',
              sort_order: 1,
              level: 3,
              pid: 290,
            },
            {
              id: 292,
              column_id: 18,
              content: '有',
              sort_order: 2,
              level: 3,
              pid: 290,
            },
          ],
        },
        {
          id: 293,
          column_id: 17,
          content: '*财务制度',
          sort_order: 2,
          level: 2,
          pid: 289,
          children: [
            {
              id: 294,
              column_id: 18,
              content: '财务制度健全',
              sort_order: 1,
              level: 3,
              pid: 293,
            },
          ],
        },
        {
          id: 295,
          column_id: 17,
          content: '*合规制度',
          sort_order: 3,
          level: 2,
          pid: 289,
          children: [
            {
              id: 296,
              column_id: 18,
              content: '合规制度健全',
              sort_order: 1,
              level: 3,
              pid: 295,
            },
          ],
        },
        {
          id: 297,
          column_id: 17,
          content: '*培训',
          sort_order: 4,
          level: 2,
          pid: 289,
          children: [
            {
              id: 298,
              column_id: 18,
              content: '业务/合规培训',
              sort_order: 1,
              level: 3,
              pid: 297,
            },
          ],
        },
      ],
    },
    {
      id: 299,
      column_id: 16,
      content: '配合度分析',
      sort_order: 3,
      level: 1,
      pid: 0,
      children: [
        {
          id: 300,
          column_id: 17,
          content: '提交的资料真实性、符合度',
          sort_order: 1,
          level: 2,
          pid: 299,
          children: [
            {
              id: 301,
              column_id: 18,
              content: '各类资料按时提交且真实，各服务项目配合度好',
              sort_order: 1,
              level: 3,
              pid: 300,
            },
            {
              id: 302,
              column_id: 18,
              content: '较为及时提交及符合要求',
              sort_order: 2,
              level: 3,
              pid: 300,
            },
            {
              id: 303,
              column_id: 18,
              content: '不按时提交或不符合要求及配合度较差',
              sort_order: 3,
              level: 3,
              pid: 300,
            },
          ],
        },
      ],
    },
  ],
  score_criteria: {
    criteria_column_id: 17,
    max_score: 100,
    total: [
      {
        cell_id: 254,
        score: 8,
      },
      {
        cell_id: 257,
        score: 10,
      },
      {
        cell_id: 260,
        score: 5,
      },
      {
        cell_id: 264,
        score: 5,
      },
      {
        cell_id: 267,
        score: 15,
      },
      {
        cell_id: 270,
        score: 10,
      },
      {
        cell_id: 274,
        score: 10,
      },
      {
        cell_id: 278,
        score: 5,
      },
      {
        cell_id: 281,
        score: 6,
      },
      {
        cell_id: 286,
        score: 6,
      },
      {
        cell_id: 290,
        score: 4,
      },
      {
        cell_id: 293,
        score: 3,
      },
      {
        cell_id: 295,
        score: 3,
      },
      {
        cell_id: 297,
        score: 3,
      },
      {
        cell_id: 300,
        score: 7,
      },
    ],
    detail: [
      {
        cell_id: 255,
        score: 8,
      },
      {
        cell_id: 256,
        score: 6,
      },
      {
        cell_id: 258,
        score: 10,
      },
      {
        cell_id: 259,
        score: 7,
      },
      {
        cell_id: 261,
        score: 5,
      },
      {
        cell_id: 262,
        score: 3,
      },
      {
        cell_id: 263,
        score: 2,
      },
      {
        cell_id: 265,
        score: 5,
      },
      {
        cell_id: 266,
        score: 3,
      },
      {
        cell_id: 268,
        score: 15,
      },
      {
        cell_id: 269,
        score: 10,
      },
      {
        cell_id: 271,
        score: 10,
      },
      {
        cell_id: 272,
        score: 8,
      },
      {
        cell_id: 273,
        score: 5,
      },
      {
        cell_id: 275,
        score: 10,
      },
      {
        cell_id: 276,
        score: 8,
      },
      {
        cell_id: 277,
        score: 5,
      },
      {
        cell_id: 279,
        score: 5,
      },
      {
        cell_id: 280,
        score: 3,
      },
      {
        cell_id: 282,
        score: 6,
      },
      {
        cell_id: 283,
        score: 5,
      },
      {
        cell_id: 284,
        score: 4,
      },
      {
        cell_id: 285,
        score: 3,
      },
      {
        cell_id: 287,
        score: 6,
      },
      {
        cell_id: 288,
        score: 4,
      },
      {
        cell_id: 291,
        score: 4,
      },
      {
        cell_id: 292,
        score: 2,
      },
      {
        cell_id: 294,
        score: 3,
      },
      {
        cell_id: 296,
        score: 3,
      },
      {
        cell_id: 298,
        score: 3,
      },
      {
        cell_id: 301,
        score: 7,
      },
      {
        cell_id: 302,
        score: 4,
      },
      {
        cell_id: 303,
        score: 3,
      },
    ],
  },
  score_options: [
    {
      cell_id: 254,
      options: [8, 6],
    },
    {
      cell_id: 257,
      options: [10, 7],
    },
    {
      cell_id: 260,
      options: [5, 3, 2],
    },
    {
      cell_id: 264,
      options: [5, 3],
    },
    {
      cell_id: 267,
      options: [15, 10],
    },
    {
      cell_id: 270,
      options: [10, 8, 5],
    },
    {
      cell_id: 274,
      options: [10, 8, 5],
    },
    {
      cell_id: 278,
      options: [5, 3],
    },
    {
      cell_id: 281,
      options: [6, 5, 4, 3],
    },
    {
      cell_id: 286,
      options: [6, 4],
    },
    {
      cell_id: 290,
      options: [4, 2],
    },
    {
      cell_id: 293,
      options: [3],
    },
    {
      cell_id: 295,
      options: [3],
    },
    {
      cell_id: 297,
      options: [3],
    },
    {
      cell_id: 300,
      options: [7, 4, 3],
    },
  ],
}
// 预览
export const tablePreview = {
  id: 6,
  name: '推广服务商等级评分表',
  desc: '推广服务商等级评分表',
  header: [
    {
      column_id: 16,
      name: '指标类别',
      sort_order: 1,
    },
    {
      column_id: 17,
      name: '具体项目',
      sort_order: 2,
    },
    {
      column_id: 18,
      name: '分数标准',
      sort_order: 3,
    },
  ],
  cell: [
    {
      id: 253,
      column_id: 16,
      content: '基础信息分析',
      sort_order: 1,
      level: 1,
      pid: 0,
      children: [
        {
          id: 254,
          column_id: 17,
          content:
            '经营资质(经营范围)：推广、技术服务、医药信息咨询、市场营销策划、企业营销策划、企业服务、企业咨询、会议及展览服务、企业管理、市场调查等',
          sort_order: 1,
          level: 2,
          pid: 253,
          children: [
            {
              id: 255,
              column_id: 18,
              content: '包含经营范围中的5项(含）以上',
              sort_order: 1,
              level: 3,
              pid: 254,
            },
            {
              id: 256,
              column_id: 18,
              content: '包含经营范围中的5项以下',
              sort_order: 2,
              level: 3,
              pid: 254,
            },
          ],
        },
        {
          id: 257,
          column_id: 17,
          content: '*注册地址及实际办公场所',
          sort_order: 2,
          level: 2,
          pid: 253,
          children: [
            {
              id: 258,
              column_id: 18,
              content:
                '*注册地与实际办公场所一致，且与推广区域一致或相近，实际办公场所为商业区且规范真实',
              sort_order: 1,
              level: 3,
              pid: 257,
            },
            {
              id: 259,
              column_id: 18,
              content: '注册地与实际办公场所不一致',
              sort_order: 2,
              level: 3,
              pid: 257,
            },
          ],
        },
        {
          id: 260,
          column_id: 17,
          content: '成立时间',
          sort_order: 3,
          level: 2,
          pid: 253,
          children: [
            {
              id: 261,
              column_id: 18,
              content: '*已成立3年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 260,
            },
            {
              id: 262,
              column_id: 18,
              content: '已成立1-3年',
              sort_order: 2,
              level: 3,
              pid: 260,
            },
            {
              id: 263,
              column_id: 18,
              content: '签协议当年成立',
              sort_order: 3,
              level: 3,
              pid: 260,
            },
          ],
        },
        {
          id: 264,
          column_id: 17,
          content: '与长典合作年限',
          sort_order: 4,
          level: 2,
          pid: 253,
          children: [
            {
              id: 265,
              column_id: 18,
              content: '2年（含）以上',
              sort_order: 1,
              level: 3,
              pid: 264,
            },
            {
              id: 266,
              column_id: 18,
              content: '2年以下',
              sort_order: 2,
              level: 3,
              pid: 264,
            },
          ],
        },
        {
          id: 267,
          column_id: 17,
          content: '*单位类型及纳税人资质',
          sort_order: 5,
          level: 2,
          pid: 253,
          children: [
            {
              id: 268,
              column_id: 18,
              content: '*有限责任公司等--一般纳税人',
              sort_order: 1,
              level: 3,
              pid: 267,
            },
            {
              id: 269,
              column_id: 18,
              content: '有限责任公司--小规模纳税人',
              sort_order: 2,
              level: 3,
              pid: 267,
            },
          ],
        },
        {
          id: 270,
          column_id: 17,
          content: '年营业收入',
          sort_order: 6,
          level: 2,
          pid: 253,
          children: [
            {
              id: 271,
              column_id: 18,
              content: '500万（含）以上',
              sort_order: 1,
              level: 3,
              pid: 270,
            },
            {
              id: 272,
              column_id: 18,
              content: '120万~500万',
              sort_order: 2,
              level: 3,
              pid: 270,
            },
            {
              id: 273,
              column_id: 18,
              content: '120万（含）以下',
              sort_order: 3,
              level: 3,
              pid: 270,
            },
          ],
        },
        {
          id: 274,
          column_id: 17,
          content: '*员工人数（实际缴纳社保人数）',
          sort_order: 7,
          level: 2,
          pid: 253,
          children: [
            {
              id: 275,
              column_id: 18,
              content: '*10人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 274,
            },
            {
              id: 276,
              column_id: 18,
              content: '4-10人',
              sort_order: 2,
              level: 3,
              pid: 274,
            },
            {
              id: 277,
              column_id: 18,
              content: '3人（含）以下',
              sort_order: 3,
              level: 3,
              pid: 274,
            },
          ],
        },
        {
          id: 278,
          column_id: 17,
          content: '推广人员人数',
          sort_order: 8,
          level: 2,
          pid: 253,
          children: [
            {
              id: 279,
              column_id: 18,
              content: '5人（含）以上',
              sort_order: 1,
              level: 3,
              pid: 278,
            },
            {
              id: 280,
              column_id: 18,
              content: '5人以下',
              sort_order: 2,
              level: 3,
              pid: 278,
            },
          ],
        },
        {
          id: 281,
          column_id: 17,
          content: '*推广人员的学历或者技能等专业能力',
          sort_order: 9,
          level: 2,
          pid: 253,
          children: [
            {
              id: 282,
              column_id: 18,
              content:
                '*占公司推广人员总人数50%以上，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 1,
              level: 3,
              pid: 281,
            },
            {
              id: 283,
              column_id: 18,
              content:
                '占公司推广人员总人数30%-50%，医药、营销相关专业或具有医药学相关的证书',
              sort_order: 2,
              level: 3,
              pid: 281,
            },
            {
              id: 284,
              column_id: 18,
              content: '30%以下',
              sort_order: 3,
              level: 3,
              pid: 281,
            },
            {
              id: 285,
              column_id: 18,
              content: '不具有相关专业学历和证书',
              sort_order: 4,
              level: 3,
              pid: 281,
            },
          ],
        },
        {
          id: 286,
          column_id: 17,
          content: '推广方案',
          sort_order: 10,
          level: 2,
          pid: 253,
          children: [
            {
              id: 287,
              column_id: 18,
              content: '有推广方案，且方案专业性强产品适用度高',
              sort_order: 1,
              level: 3,
              pid: 286,
            },
            {
              id: 288,
              column_id: 18,
              content: '有提供',
              sort_order: 2,
              level: 3,
              pid: 286,
            },
          ],
        },
      ],
    },
    {
      id: 289,
      column_id: 16,
      content: '管理分析',
      sort_order: 2,
      level: 1,
      pid: 0,
      children: [
        {
          id: 290,
          column_id: 17,
          content: '*组织结构',
          sort_order: 1,
          level: 2,
          pid: 289,
          children: [
            {
              id: 291,
              column_id: 18,
              content: '有，且有专门推广部门',
              sort_order: 1,
              level: 3,
              pid: 290,
            },
            {
              id: 292,
              column_id: 18,
              content: '有',
              sort_order: 2,
              level: 3,
              pid: 290,
            },
          ],
        },
        {
          id: 293,
          column_id: 17,
          content: '*财务制度',
          sort_order: 2,
          level: 2,
          pid: 289,
          children: [
            {
              id: 294,
              column_id: 18,
              content: '财务制度健全',
              sort_order: 1,
              level: 3,
              pid: 293,
            },
          ],
        },
        {
          id: 295,
          column_id: 17,
          content: '*合规制度',
          sort_order: 3,
          level: 2,
          pid: 289,
          children: [
            {
              id: 296,
              column_id: 18,
              content: '合规制度健全',
              sort_order: 1,
              level: 3,
              pid: 295,
            },
          ],
        },
        {
          id: 297,
          column_id: 17,
          content: '*培训',
          sort_order: 4,
          level: 2,
          pid: 289,
          children: [
            {
              id: 298,
              column_id: 18,
              content: '业务/合规培训',
              sort_order: 1,
              level: 3,
              pid: 297,
            },
          ],
        },
      ],
    },
    {
      id: 299,
      column_id: 16,
      content: '配合度分析',
      sort_order: 3,
      level: 1,
      pid: 0,
      children: [
        {
          id: 300,
          column_id: 17,
          content: '提交的资料真实性、符合度',
          sort_order: 1,
          level: 2,
          pid: 299,
          children: [
            {
              id: 301,
              column_id: 18,
              content: '各类资料按时提交且真实，各服务项目配合度好',
              sort_order: 1,
              level: 3,
              pid: 300,
            },
            {
              id: 302,
              column_id: 18,
              content: '较为及时提交及符合要求',
              sort_order: 2,
              level: 3,
              pid: 300,
            },
            {
              id: 303,
              column_id: 18,
              content: '不按时提交或不符合要求及配合度较差',
              sort_order: 3,
              level: 3,
              pid: 300,
            },
          ],
        },
      ],
    },
  ],
  score_criteria: {
    criteria_column_id: 17,
    max_score: 100,
    total: [
      {
        cell_id: 254,
        score: 8,
      },
      {
        cell_id: 257,
        score: 10,
      },
      {
        cell_id: 260,
        score: 5,
      },
      {
        cell_id: 264,
        score: 5,
      },
      {
        cell_id: 267,
        score: 15,
      },
      {
        cell_id: 270,
        score: 10,
      },
      {
        cell_id: 274,
        score: 10,
      },
      {
        cell_id: 278,
        score: 5,
      },
      {
        cell_id: 281,
        score: 6,
      },
      {
        cell_id: 286,
        score: 6,
      },
      {
        cell_id: 290,
        score: 4,
      },
      {
        cell_id: 293,
        score: 3,
      },
      {
        cell_id: 295,
        score: 3,
      },
      {
        cell_id: 297,
        score: 3,
      },
      {
        cell_id: 300,
        score: 7,
      },
    ],
    detail: [
      {
        cell_id: 255,
        score: 8,
      },
      {
        cell_id: 256,
        score: 6,
      },
      {
        cell_id: 258,
        score: 10,
      },
      {
        cell_id: 259,
        score: 7,
      },
      {
        cell_id: 261,
        score: 5,
      },
      {
        cell_id: 262,
        score: 3,
      },
      {
        cell_id: 263,
        score: 2,
      },
      {
        cell_id: 265,
        score: 5,
      },
      {
        cell_id: 266,
        score: 3,
      },
      {
        cell_id: 268,
        score: 15,
      },
      {
        cell_id: 269,
        score: 10,
      },
      {
        cell_id: 271,
        score: 10,
      },
      {
        cell_id: 272,
        score: 8,
      },
      {
        cell_id: 273,
        score: 5,
      },
      {
        cell_id: 275,
        score: 10,
      },
      {
        cell_id: 276,
        score: 8,
      },
      {
        cell_id: 277,
        score: 5,
      },
      {
        cell_id: 279,
        score: 5,
      },
      {
        cell_id: 280,
        score: 3,
      },
      {
        cell_id: 282,
        score: 6,
      },
      {
        cell_id: 283,
        score: 5,
      },
      {
        cell_id: 284,
        score: 4,
      },
      {
        cell_id: 285,
        score: 3,
      },
      {
        cell_id: 287,
        score: 6,
      },
      {
        cell_id: 288,
        score: 4,
      },
      {
        cell_id: 291,
        score: 4,
      },
      {
        cell_id: 292,
        score: 2,
      },
      {
        cell_id: 294,
        score: 3,
      },
      {
        cell_id: 296,
        score: 3,
      },
      {
        cell_id: 298,
        score: 3,
      },
      {
        cell_id: 301,
        score: 7,
      },
      {
        cell_id: 302,
        score: 4,
      },
      {
        cell_id: 303,
        score: 3,
      },
    ],
  },
  score_options: [
    {
      cell_id: 254,
      options: [8, 6],
    },
    {
      cell_id: 257,
      options: [10, 7],
    },
    {
      cell_id: 260,
      options: [5, 3, 2],
    },
    {
      cell_id: 264,
      options: [5, 3],
    },
    {
      cell_id: 267,
      options: [15, 10],
    },
    {
      cell_id: 270,
      options: [10, 8, 5],
    },
    {
      cell_id: 274,
      options: [10, 8, 5],
    },
    {
      cell_id: 278,
      options: [5, 3],
    },
    {
      cell_id: 281,
      options: [6, 5, 4, 3],
    },
    {
      cell_id: 286,
      options: [6, 4],
    },
    {
      cell_id: 290,
      options: [4, 2],
    },
    {
      cell_id: 293,
      options: [3],
    },
    {
      cell_id: 295,
      options: [3],
    },
    {
      cell_id: 297,
      options: [3],
    },
    {
      cell_id: 300,
      options: [7, 4, 3],
    },
  ],
}
